### ISSUE TITLE
Exercise 1a widget template name

### ISSUE THREAD

**Issue by dmytroyarmak** [Backbase/training-fe-module-01#10]
Hi,
In exercise 1a in step 1 there is a sentence: 

> Scaffold a "Todo" widget structure using the bb generate command of bb-cli (generate an lp56-widget)

but I couldn't find the `lp56-widget` template in bb-cli. Shouldn't it be just `lp-widget`?

**Comment by salvitas** [comment]
Hi,
Yes it changed through different versions it depends on the branch but latest is only lp-widget you are right.
